dist: trusty
language: go

go:
    - tip
    - 1.9
    - 1.8

services:
    - redis

install:
    - go get ./...

env:
    - TEST_REDIS_ADDRESSES=localhost:6379

before_script:
    - sh -c "sleep 5"  # give Redis a(n additional) chance to start

script:
    - go test -v ./...

